name: 'Setup Node.js and Install Dependencies'
description: 'Sets up Node.js with caching and installs npm dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
