import type { Database } from 'src/db/database.types';

// ################################################################# //
// ###################### DATABASE TYPE ALIASES #################### //
// ################################################################# //

/** Represents a single row from the `flashcards` table. */
export type Flashcard = Database['public']['Tables']['flashcards']['Row'];

/** Represents a single row from the `generations` table. */
export type Generation = Database['public']['Tables']['generations']['Row'];

/** Represents a single row from the `generation_error_logs` table. */
export type GenerationErrorLog =
  Database['public']['Tables']['generation_error_logs']['Row'];

/**
 * Defines the allowed sources for a flashcard, indicating how it was created.
 * - `manual`: Created manually by the user.
 * - `ai-full`: Generated by AI and accepted without edits.
 * - `ai-edited`: Generated by AI and edited by the user before saving.
 */
export type FlashcardSource = 'ai-full' | 'ai-edited' | 'manual';

// ################################################################# //
// ######################### BASE DTO TYPES ######################## //
// ################################################################# //

/**
 * Represents the public-facing data for a single flashcard.
 * It excludes sensitive or internal fields like user_id and the full-text search vector.
 * This DTO is used in API responses for `GET /flashcards` and `GET /flashcards/{id}`.
 */
export type FlashcardDto = Omit<
  Flashcard,
  'user_id' | 'fts_vector'
>;

/**
 * Represents the structure for pagination information accompanying list responses.
 */
export interface PaginationDto {
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

/**
 * Represents the paginated response for the `GET /flashcards` endpoint.
 */
export interface PaginatedFlashcardsDto {
  data: FlashcardDto[];
  pagination: PaginationDto;
}


/**
 * Represents a flashcard presented during a review session (`GET /reviews`).
 * This is a minimal representation containing only the fields necessary for studying.
 */
export type ReviewFlashcardDto = Pick<Flashcard, 'id' | 'front' | 'back'>;

// ################################################################# //
// ######################## COMMAND MODELS ######################### //
// ################################################################# //

// --------------------- Flashcards Commands --------------------- //

/**
 * Command model for manually creating a single flashcard (`POST /flashcards`).
 * The `source` is set to 'manual' by the backend.
 * The `user_id` is derived from the authenticated session.
 */
export interface FlashcardCreateDto {
    front: string;
    back: string;
    source: FlashcardSource;
    generation_id: number | null;
}


/**
 * Represents a single flashcard item within a batch creation request.
 * The `source` field is required to track whether the user accepted the AI suggestion as-is ('ai-full')
 * or edited it before saving ('ai-edited').
 * We use our custom `FlashcardSource` type here to enforce the correct string literals,
 * as the auto-generated DB type for `source` is a generic `string`.
 */
type BatchCreateFlashcardItem = Pick<
  Database['public']['Tables']['flashcards']['Insert'],
  'front' | 'back'
> & {
  source: FlashcardSource;
};

/**
 * Command model for creating a batch of flashcards (`POST /flashcards/batch`).
 * This is used after the user reviews AI-generated suggestions.
 * The `generation_id` links the created flashcards back to the original generation session for metrics.
 */
export interface CreateFlashcardsBatchCommand {
  generation_id: Generation['id'];
  flashcards: BatchCreateFlashcardItem[];
}

/**
 * Command model for updating an existing flashcard (`PUT /flashcards/{id}`).
 * It requires the `front` and `back` fields to be provided for a full update.
 */
export type UpdateFlashcardCommand = Partial<{
    front: string;
    back: string;
    source: FlashcardSource;
    generation_id: number | null;
}>;

// --------------------- Generations Commands --------------------- //

/**
 * Command model for initiating an AI flashcard generation session (`POST /generations`).
 * Requires a `source_text` that meets the length constraints defined in the database.
 */
export interface CreateGenerationCommand {
  source_text: string;
}

// ################################################################# //
// ################### API RESPONSE DTOs ################### //
// ################################################################# //

/**
 * Represents a flashcard suggestion generated by the AI.
 * This is a transient object that is not stored in the database as-is;
 * it is presented to the user for review.
 */
export interface SuggestedFlashcardDto {
    front: string;
    back: string;
    source: 'ai-full';
}

/**
 * Represents the successful response payload from the `POST /generations` endpoint.
 * It provides the `generation_id` to be used when committing the reviewed flashcards
 * and a list of `suggested_flashcards` for the user to review.
 */
export interface CreateGenerationResponseDto {
  generation_id: Generation['id'];
  suggested_flashcards: SuggestedFlashcardDto[];
  generated_count: number;
}

export type GenerationDetailsDto = Generation & {
  accepted_flashcards: FlashcardDto[];
};

export type GenerationErrorLogDto = Pick<
    GenerationErrorLog,
    'id' | 'error_code' | 'error_message' | 'model' | 'source_text_hash' | 'source_text_length' | 'created_at' | 'user_id'
  >;